import requests
import base64
from backend.src.config.settings import settings
from backend.src.utils.logger import get_logger

logger = get_logger(__name__)


def generate_meme_image(prompt: str):
    """
    Generate a meme image using OpenRouter API with Gemini 2.5 Flash Image model.
    Takes a full prompt (generated by prompt_generator) and returns image bytes.
    """
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {settings.OPENROUTER_API_KEY}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "google/gemini-2.5-flash-image-preview",
        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ],
        "modalities": ["image", "text"],
        "image_config": {
            "aspect_ratio": "1:1"  # Square format for Instagram
        }
    }

    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status()
        result = response.json()

        if result.get("choices"):
            message = result["choices"][0]["message"]
            if message.get("images"):
                # Get the first image
                image = message["images"][0]
                image_url = image["image_url"]["url"]
                
                # Extract base64 data from data URL
                if image_url.startswith("data:image"):
                    # Format: data:image/png;base64,<base64_data>
                    header, base64_data = image_url.split(",", 1)
                    
                    # Decode to bytes
                    image_bytes = base64.b64decode(base64_data)
                    logger.info(f"Generated image ({len(image_bytes)} bytes)")
                    
                    # Return a simple object that mimics the expected structure
                    class ImageResponse:
                        def __init__(self, image_bytes):
                            self.candidates = [ImageCandidate(image_bytes)]
                    
                    class ImageCandidate:
                        def __init__(self, image_bytes):
                            self.generated_images = [GeneratedImage(image_bytes)]
                    
                    class GeneratedImage:
                        def __init__(self, image_bytes):
                            self.image = image_bytes
                    
                    return ImageResponse(image_bytes)
                else:
                    raise ValueError(f"Unexpected image URL format: {image_url[:50]}...")
            else:
                raise ValueError("No images in API response")
        else:
            raise ValueError("No choices in API response")
    
    except Exception as e:
        logger.error(f"Error generating meme image: {str(e)}")
        raise
